FROM python:3
ENV PYTHONUNBUFFERED 1

# Support PostgreSQL
RUN apt-get update && apt-get -y install libpq-dev

RUN mkdir /app
WORKDIR /app

COPY ./requirements.txt /app/
RUN pip install -r requirements.txt
